### ISSUE TITLE
frequencies2csv error: row names missing values

### ISSUE THREAD

**Issue by numskull** [michaelgavin/tei2r#6]
> frequencies2csv(df, "freqs.csv")
> Error in data.frame(word, frequency, space, stringsAsFactors = F) : 
>   row names contain missing values

**Comment by michaelgavin** [comment]
hard to say for sure what caused your error. my guess is that the df object was corrupt in some way. In any case, I changed the function around just a little: now it saves by default into the working directory, rather than in the folder with the data files. I also suppressed a little warning. Anyway, seems to work fine.
